source/applicants/urls.py
from django.urls import path

from applicants.views.applicants import ApplicantDetailView, ApplicantUpdateView, ApplicantChangePasswordView
from applicants.views.resumes import ResumeCreateView, ResumeDetailView, ResumeUpdateView, ResumeDeleteView, \
    resume_update_data

urlpatterns = [
    # URL для Соискателя
    path('applicants/<int:pk>/detail', ApplicantDetailView.as_view(), name='applicant_detail'),
    path('applicants/<int:pk>/update', ApplicantUpdateView.as_view(), name='applicant_update'),
    path('applicants/<int:pk>/change_password', ApplicantChangePasswordView.as_view(),
         name='applicant_change_password'),

    # URL для Резюме
    path('resumes/create/', ResumeCreateView.as_view(), name='resume_create'),
    path('resumes/<int:pk>/detail/', ResumeDetailView.as_view(), name='resume_detail'),
    path('resumes/<int:pk>/update/', ResumeUpdateView.as_view(), name='resume_update'),
    path('resumes/<int:pk>/delete/', ResumeDeleteView.as_view(), name='resume_delete'),
    path('resumes/<int:pk>/update_data', resume_update_data, name='resume_update_data')
]

source/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from main.views import IndexView

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('auth/', include('accounts.urls')),
    path('', include('applicants.urls')),
    path('', include('employers.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/applicants/models/experience.py
from django.db import models


class Experience(models.Model):
    resume = models.ForeignKey(
        'Resume',
        related_name='experiences',
        on_delete=models.CASCADE,
        verbose_name='Резюме',
    )
    company = models.CharField(
        max_length=512,
        null=False,
        blank=False,
        verbose_name='Название компании',
    )
    obligations = models.TextField(
        max_length=4096,
        null=False,
        blank=False,
        verbose_name='Описание работы',
    )
    position = models.CharField(
        max_length=128,
        null=False,
        blank=False,
        verbose_name='Занимаемая должность',
    )
    started_at = models.DateTimeField(
        verbose_name="Дата начала"
    )
    ended_at = models.DateTimeField(
        null=True,
        verbose_name='Дата окончания',
    )

    def __str__(self):
        return f'{self.company} - {self.position[:40]}'

    class Meta:
        verbose_name = 'Опыт'
        verbose_name_plural = 'Опыт'

source/applicants/models/resume.py
from django.conf import settings
from django.db import models
from django.utils import timezone


class Resume(models.Model):
    applicant = models.ForeignKey(
        to=settings.AUTH_USER_MODEL,
        verbose_name='Соискатель',
        related_name='resumes',
        null=False,
        blank=False,
        on_delete=models.CASCADE
    )
    full_name = models.CharField(
        max_length=256,
        null=False,
        blank=False,
        verbose_name='Полное имя'
    )
    position = models.CharField(
        max_length=128,
        null=False,
        blank=False,
        verbose_name='Должность'
    )
    salary = models.PositiveIntegerField(
        null=False,
        blank=False,
        verbose_name='Желаемая зарплата'
    )
    about = models.TextField(
        max_length=2000,
        null=False,
        blank=False,
        verbose_name='О себе'
    )
    telegram = models.CharField(
        max_length=256,
        null=False,
        blank=False,
        verbose_name='Nickname telegram'
    )
    facebook = models.CharField(
        max_length=512,
        null=True,
        blank=True,
        verbose_name='Facebook profile URL'
    )
    linkedin = models.CharField(
        max_length=512,
        null=True,
        blank=True,
        verbose_name='Linkedin profile URL'
    )
    is_deleted = models.BooleanField(
        verbose_name='Удалено',
        null=False,
        default=False
    )
    is_published = models.BooleanField(
        null=False,
        blank=False,
        default=True,
        verbose_name='Статус публикации'
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Дата создания"
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name="Дата обновления",
        null=True
    )

    def __str__(self):
        return f'{self.full_name} - {self.position[:25]}'

    def delete(self, using=None, keep_parents=False):
        self.is_deleted = True
        self.deleted_at = timezone.now()
        self.save()

    class Meta:
        verbose_name = 'Резюме'
        verbose_name_plural = 'Резюме'

source/applicants/models/skills.py
from django.db import models


class Skill(models.Model):
    name = models.CharField(
        max_length=100,
        null=False,
        blank=False,
        verbose_name='Навык'
    )

    def __str__(self):
        return self.name

source/applicants/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import inlineformset_factory

from applicants.models import Resume, Experience


class ResumeForm(forms.ModelForm):
    class Meta:
        model = Resume
        fields = ('full_name', 'position', 'salary', 'about', 'telegram', 'facebook', 'linkedin')

    def clean_full_name(self):
        full_name = self.cleaned_data.get('full_name')
        if len(full_name) < 8:
            raise ValidationError('Полное имя должно быть длинее 8-и символов')
        return full_name


class ExperienceForm(forms.ModelForm):
    class Meta:
        model = Experience
        fields = ('company', 'obligations', 'position', 'started_at', 'ended_at')


experience_form_set = inlineformset_factory(
    Resume,
    Experience,
    form=ExperienceForm
)

source/applicants/views.py
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse
from django.views.generic import ListView, FormView

from accounts.forms import AccountChangePasswordForm, AccountUpdateForm
from accounts.models import Account
from applicants.models import Resume


# Create your views here.


class ApplicantDetailView(ListView):
    template_name = 'applicants/applicant_detail.html'
    model = Resume
    ordering = ('-created_at',)
    paginate_orphans = 1
    paginate_by = 3

    def get_queryset(self):
        applicant_id = self.kwargs.get('pk')
        return Resume.objects.filter(applicant_id=applicant_id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        applicant = Account.objects.get(pk=self.kwargs.get('pk'))
        context['applicant_id'] = applicant.id
        context['applicant_email'] = applicant.email
        context['applicant_name'] = applicant.name
        context['applicant_phone'] = applicant.phone
        context['applicant_avatar'] = applicant.avatar
        context['account_change_form'] = AccountUpdateForm(instance=applicant)
        context['change_password_form'] = AccountChangePasswordForm(instance=applicant)
        return context


class ApplicantUpdateView(FormView):
    form_class = AccountUpdateForm

    def post(self, request, *args, **kwargs):
        applicant = get_object_or_404(Account, pk=self.kwargs.get('pk'))
        form = self.get_form_class()(request.POST, instance=applicant)
        print(form)
        if form.is_valid():
            form.save()
        return reverse('applicant_detail', kwargs={'pk': applicant.pk})


class ApplicantChangePasswordView(FormView):
    form_class = AccountChangePasswordForm

    def post(self, request, *args, **kwargs):
        applicant = get_object_or_404(Account, pk=self.kwargs.get('pk'))
        form = self.get_form_class()(request.POST, instance=applicant)
        if form.is_valid():
            form.save()
        return redirect('applicant_detail', pk=applicant.pk)

source/applicants/views/applicants.py
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import ListView, FormView

from accounts.forms import AccountChangePasswordForm, AccountUpdateForm
from accounts.models import Account
from applicants.models import Resume


# Create your views here.


class ApplicantDetailView(ListView):
    template_name = 'applicants/applicant_detail.html'
    model = Resume
    ordering = ('-created_at',)
    paginate_orphans = 1
    paginate_by = 3

    def get_queryset(self):
        applicant_id = self.kwargs.get('pk')
        return Resume.objects.filter(applicant_id=applicant_id).exclude(is_deleted=True)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        applicant = Account.objects.get(pk=self.kwargs.get('pk'))
        context['applicant_id'] = applicant.id
        context['applicant_email'] = applicant.email
        context['applicant_name'] = applicant.name
        context['applicant_phone'] = applicant.phone
        context['applicant_avatar'] = applicant.avatar
        context['account_change_form'] = AccountUpdateForm(instance=applicant)
        context['change_password_form'] = AccountChangePasswordForm(instance=applicant)
        return context


class ApplicantUpdateView(FormView):
    form_class = AccountUpdateForm

    def post(self, request, *args, **kwargs):
        applicant = get_object_or_404(Account, pk=self.kwargs.get('pk'))
        form = self.get_form_class()(request.POST, instance=applicant)
        print(form)
        if form.is_valid():
            form.save()
        return redirect('applicant_detail', pk=applicant.pk)


class ApplicantChangePasswordView(FormView):
    form_class = AccountChangePasswordForm

    def post(self, request, *args, **kwargs):
        applicant = get_object_or_404(Account, pk=self.kwargs.get('pk'))
        form = self.get_form_class()(request.POST, instance=applicant)
        if form.is_valid():
            form.save()
        return redirect('applicant_detail', pk=applicant.pk)

source/applicants/views/resumes.py
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.utils import timezone
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView

from applicants.forms import ResumeForm, experience_form_set
from applicants.models import Resume


class ResumeDetailView(DetailView):
    template_name = 'resumes/resume_detail.html'
    model = Resume

    def get(self, request, *args, **kwargs):
        context = super().get(request, *args, **kwargs)
        resume = get_object_or_404(Resume, pk=kwargs['pk'])
        if resume.is_deleted == True:
            raise Http404
        return context


# class ResumeCreateView(CreateView):
#     template_name = 'resumes/resume_create.html'
#     model = Resume
#     form_class = ResumeForm
#
#     def get_success_url(self):
#         return reverse('applicant_detail', kwargs={'pk': self.request.user.pk})
#
#     def form_valid(self, form):
#         resume = form.save(commit=False)
#         resume.applicant = self.request.user
#         resume.save()
#         return super().form_valid(form)

class ResumeCreateView(CreateView):
    template_name = 'resumes/resume_create.html'
    model = Resume
    form_class = ResumeForm

    def get_success_url(self):
        return reverse('applicant_detail', kwargs={'pk': self.request.user.pk})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['experience_form_set'] = experience_form_set(self.request.POST)
        else:
            context['experience_form_set'] = experience_form_set()
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        experience_form_set = context['experience_form_set']
        if experience_form_set.is_valid():
            resume = form.save(commit=False)
            resume.applicant = self.request.user
            resume.save()
            experience_form_set.instance = resume
            experience_form_set.save()
            return redirect(self.get_success_url())
        else:
            render(self.request, self.template_name, context=self.get_context_data(form=form))


class ResumeUpdateView(UpdateView):
    template_name = 'resumes/resume_update.html'
    model = Resume
    form_class = ResumeForm

    def get_success_url(self):
        return reverse('applicant_detail', kwargs={'pk': self.request.user.pk})


class ResumeDeleteView(DeleteView):
    model = Resume

    def get_success_url(self):
        return reverse('applicant_detail', kwargs={'pk': self.request.user.pk})


def resume_update_data(request, pk):
    resume = get_object_or_404(Resume, pk=pk)
    resume.updated_at = timezone.now()
    resume.save()
    return redirect('resume_detail', resume.pk)

source/applicants/templates/applicants/applicant_detail.html
{% extends 'base.html' %}

    {% block title %}{% endblock %}

{% block content %}
<h3>Личный кабинет соискателя {{ applicant_name }}</h3>
{#Модальное окно#}
{% include 'applicants/includes/modal_change.html' %}


<section class="applicant-info" style="margin-top: 20px;">
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-2">
                {% if applicant_avatar %}
                    <img src="{{ applicant_avatar.url }}" class="img-fluid" alt="{{ applicant_name }}">
                {% else %}
                    <img src="/uploads/user_pic/no_image.jpeg" class="img-fluid" alt="{{ applicant_name }}">
                {% endif %}
            </div>
            <div class="col-4">
                <table class="table">
                    <tbody>
                    <tr>
                        <th scope="row">Имя</th>
                        <td>{{ applicant_name }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Email</th>
                        <td>{{ applicant_email }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Телефон</th>
                        <td colspan="">{{ applicant_phone }}</td>
                    </tr>
                    {% if applicant_id == user.id %}
                    <tr>
                        <td colspan="1">
                            <button type="button" class="btn btn-primary" data-bs-toggle="modal"
                                    data-bs-target="#exampleModal">
                                Редактировать
                            </button>
                        </td>
                        <td colspan="2">
                            <a href="{% url 'resume_create' %}" class="btn btn-primary">
                                Создать резюме
                            </a>
                        </td>
                    </tr>
                    {% endif %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>

<section class="resume-list" style="margin-top: 50px">
    <div class="container">
        <div class="row">
            {% if resume_list %}
                {% for resume in resume_list %}
                    <div class="col-3">
                        <div class="card" style="width: 18rem;">
                            <div class="card-body">
                                <h5 class="card-title">{{ resume.position }}</h5>
                                <p class="card-text">{{ resume.full_name }}</p>
                                <p class="card-text">Желаемая зарплата: {{ resume.salary }}</p>
                                <a href="{% url 'resume_detail' resume.pk %}" class="btn btn-primary">Подробнее</a>
                                {% if applicant_id == user.id %}
                                <a href="{% url 'resume_update' resume.pk %}" class="btn btn-primary"
                                   style="margin-top: 20px">Редактировать</a>
                                <a href="{% url 'resume_update_data' resume.pk %}" class="btn btn-primary"
                                   style="margin-top: 20px">Обновить</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <h5>У вас еще нет резюме</h5>
            {% endif %}
        </div>
        {% if is_paginated %}
            {% include 'applicants/includes/pagination.html' %}
        {% endif %}
    </div>
</section>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
        crossorigin="anonymous"></script>
{% endblock %}